Ticket/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Ticket.Filters;
using Ticket.Models;
using Ticket.Models.Context;

namespace Ticket.Controllers
{
    [LogFilter]
    public class SignInController : Controller
    {
        // GET: SignIn
        public ActionResult Index()
        {
            return View(new Users());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Index(Users user)
        {
            DatabaseContext db = new DatabaseContext();
            List<Users> usersList = db.Users.Where(x => !x.IsDeleted).ToList();
            foreach (Users u in usersList)
            {
                if (u.Email == user.Email && u.Password == Crypto.Hash(user.Password))
                {
                    Session["Login"] = u.Username;
                    if (u.IsAdmin)
                    {
                        Session["Admin"] = u.Username;
                        return RedirectToAction("Index", "Admin");
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", "E-posta veya şifre yanlış.");

            return View(user);
        }
    }
}

Ticket/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Ticket.Filters;
using Ticket.Models;
using Ticket.Models.Context;
using Ticket.ViewModels;
using Ticket = Ticket.Models.Ticket;

namespace Ticket.Controllers
{
    [LogFilter]
    [AuthFilter]
    public class TicketsController : Controller
    {
        private readonly List<string> acceptedExtensions = new List<string>()
        {
            ".pdf",
            ".xls",
            ".xlsx",
            ".jpg",
            ".docx",
            ".doc",
            ".jpeg"
        };

        // GET: Tickets
        public ActionResult Index(string sortby = "-date")
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Index", "SignIn");
            }
            DatabaseContext db = new DatabaseContext();
            List<Models.Users> users = db.Users.Where(x => !x.IsDeleted).ToList();
            foreach (Users u in users)
            {
                if (Session["Login"].ToString() == u.Username)
                {
                    if (sortby == "name")
                    {
                        u.Tickets = u.Tickets.OrderBy(o => o.Title).ToList();
                    }
                    else if (sortby == "-name")
                    {
                        u.Tickets = u.Tickets.OrderByDescending(o => o.Title).ToList();
                    }
                    else if (sortby == "date")
                    {
                        u.Tickets = u.Tickets.OrderBy(o => o.DateTime).ToList();
                    }
                    if (sortby == "-date")
                    {
                        u.Tickets = u.Tickets.OrderByDescending(o => o.DateTime).ToList();
                    }
                    else if (sortby == "status")
                    {
                        u.Tickets = u.Tickets.OrderBy(o => o.Status).ToList();
                    }
                    else if (sortby == "-status")
                    {
                        u.Tickets = u.Tickets.OrderByDescending(o => o.Status).ToList();
                    }
                    else if (sortby == "type")
                    {
                        u.Tickets = u.Tickets.OrderBy(o => o.Type).ToList();
                    }
                    else if (sortby == "-type")
                    {
                        u.Tickets = u.Tickets.OrderByDescending(o => o.Type).ToList();
                    }

                    u.Tickets = u.Tickets.Where(t => !t.IsDeleted).ToList();
                    return View(u);
                }
            }

            return RedirectToAction("Index", "SignIn");
        }

        public ActionResult Create()
        {
            TicketwithListViewModel model = new TicketwithListViewModel();

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(TicketwithListViewModel t, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(t);
            }

            if (file != null)
            {
                if (file != null)
                {
                    if (acceptedExtensions.Contains(Path.GetExtension(file.FileName)))
                    {
                        if (!Directory.Exists(Server.MapPath("~/userfiles")))
                        {
                            Directory.CreateDirectory(Server.MapPath("~/userfiles"));
                        }
                        file.SaveAs(Path.Combine(Server.MapPath("~/userfiles"), file.FileName));
                        t.Ticket.FilePath = Path.Combine(Server.MapPath("~/userfiles"), file.FileName);
                    }
                    else
                    {
                        @ViewBag.file = "Bu dosya tipi Desteklenmemektedir";
                        return View(t);
                    }
                }
            }
            DatabaseContext db = new DatabaseContext();
            List<Users> userslist = db.Users.Where(x => !x.IsDeleted).ToList();
            foreach (Users u in userslist)
            {
                if (u.Username == Session["Login"].ToString())
                {
                    t.Ticket.Author = u;
                }
            }
            db.Tickets.Add(t.Ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Ticket(int id)
        {
            DatabaseContext db = new DatabaseContext();
            Models.Ticket t = db.Tickets.Find(id);
            if (t.IsDeleted)
            {
                return View();
            }

            return View(t);
        }

        public ActionResult EditProfile()
        {
            DatabaseContext db = new DatabaseContext();
            foreach (Users users in db.Users.Where(x => !x.IsDeleted).ToList())
            {
                if (users.Username == Session["Login"].ToString())
                {
                    return View(users);
                }
            }

            return RedirectToAction("Index", "SignIn");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditProfile(Users model)
        {
            DatabaseContext db = new DatabaseContext();
            List<Users> userslList = db.Users.Where(x => !x.IsDeleted).ToList();
            Users old = null;
            Log l = null;

            Users updateUser = new Users();
            int result = 0;
            int changes = 0;
            foreach (Users u in userslList)
            {
                if (u.Username != Session["Login"].ToString() && u.Email == model.Email && !u.IsDeleted)
                {
                    ViewBag.status = "warning";
                    ViewBag.result = "Bu E-mail adresi kullanılmaktadır.";
                    return View(updateUser);
                }

                if (u.Username != Session["Login"].ToString() && u.Username == model.Username && !u.IsDeleted)
                {
                    ViewBag.status = "warning";
                    ViewBag.result = "Bu kullanıcı adı kullanılmaktadır.";
                    return View(updateUser);
                }
                if (u.Username == Session["Login"].ToString() && !u.IsDeleted)
                {
                    updateUser = u;
                }
            }

            if (ModelState.IsValid)
            {
                if (Crypto.Hash(model.Password) != updateUser.Password)
                {
                    ViewBag.status = "danger";
                    ViewBag.result = "Şifre Yanlış.";
                    return View(updateUser);
                }
                else
                {
                    old = new Users(updateUser) { IsDeleted = true };
                    l = new Log
                    {
                        ObjecType = typeof(Users).ToString(),
                        Type = "Modified",
                        PreviousUsers = old,
                        IP = HttpContext.Request.UserHostAddress,
                        Time = DateTime.Now,
                        routevalues = HttpContext.Request.Url.PathAndQuery
                    };
                    if (old.Tickets != null)
                    {
                        foreach (Models.Ticket t in old.Tickets)
                        {
                            t.IsDeleted = true;
                        }
                    }

                    Session["Login"] = model.Username;
                    updateUser.Name = model.Name;
                    updateUser.Surname = model.Surname;
                    updateUser.Username = model.Username;
                    updateUser.Email = model.Email;

                    changes = db.ChangeTracker.Entries().Where(x => x.State != EntityState.Unchanged).ToList().Count;

                    result = db.SaveChanges();
                }
            }

            if (changes > 0)
            {
                if (old != null)
                {
                    db.Users.Add(old);
                }

                if (l != null)
                {
                    l.NextUsers = updateUser;

                    l.Users = updateUser;

                    db.Logs.Add(l);
                }
                if (result > 0)
                {
                    ViewBag.status = "success";
                    ViewBag.result = "Değişiklikler Kaydedilmiştir.";
                }
                else
                {
                    ViewBag.status = "danger";
                    ViewBag.result = "Değişiklikler Kaydedilememiştir.";
                }
            }
            else
            {
                ViewBag.status = "warning";
                ViewBag.result = "Değişiklik Olmamıştır.";
            }
            db.SaveChanges();

            return View(updateUser);
        }

        public ActionResult EditTicket(int id)
        {
            DatabaseContext db = new DatabaseContext();
            Models.Ticket model = db.Tickets.Find(id);
            if (model.IsDeleted)
            {
                return View();
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditTicket(Models.Ticket model, int id, HttpPostedFileBase file)
        {
            DatabaseContext db = new DatabaseContext();

            Models.Ticket updateTicket = db.Tickets.Find(id);
            Models.Ticket old = null;
            if (ModelState.IsValid && !updateTicket.IsDeleted)
            {
                string user = Session["Login"].ToString();
                old = new Models.Ticket(updateTicket) { IsDeleted = true };

                updateTicket.Type = model.Type;
                updateTicket.Text = model.Text;

Ticket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Favicon -->
    <link href="~/assets/img/brand/favicon.png" rel="icon" type="image/png">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <!-- Icons -->
    <link href="~/assets/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link href="~/assets/vendor/fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <link href="~/Material-Time-Picker-Plugin-jQuery-MDTimePicker/mdtimepicker.css" rel="stylesheet" />
    <!-- Argon CSS -->
    <link type="text/css" href="/assets/css/argon.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-horizontal navbar-expand-lg navbar-dark bg-default mb-4">
        <div class="container">
            @if (Session["Admin"] != null)
            {
                @Html.ActionLink("Ticket Sistemi", "Index", "Admin", null, new { @class = "navbar-brand", id = "navbar-brand" })

            }
            else
            {
                @Html.ActionLink("Ticket Sistemi", "Index", "Home", null, new { @class = "navbar-brand", id = "navbar-brand" })

            }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-primary">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="javascript:void(0)">
                                <img src="../../assets/img/brand/blue.png">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav ml-lg-auto">
                    @if (Session["Login"] == null)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link nav-link-icon btn btn-outline-default" href="#" id="navbar-primary_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ni ni-single-02 "> </i><span class="nav-link-inner--text"><strong>Giriş Yap </strong></span></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-primary_dropdown_1">
                                @Html.ActionLink("Giriş Yap", "Index", "SignIn", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Kayıt Ol", "Index", "Register", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link btn btn-outline-default" href="#" id="navbar-primary_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ni ni-single-02 "></i><strong class="nav-link-inner--text">@Session["Login"].ToString() </strong></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-primary_dropdown_1">
                                @Html.ActionLink("Ayarlar", "EditProfile", "Tickets", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Çıkış Yap", "SignOut", "Home", null, new { @class = "dropdown-item" })
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link nav-link-icon " href="/Tickets"> <i class="ni ni-archive-2"></i><strong class="nav-link-inner--text">Biletlerim</strong></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link nav-link-icon " href="/Tickets/Create"> <i class="ni ni-send"></i><strong class="nav-link-inner--text">Bilet Ekle</strong></a>
                        </li>
                        if (Session["Admin"] != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link nav-link-icon " href="/Admin/Logs">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-list-task" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z" />
                                        <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z" />
                                        <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z" />
                                    </svg><strong class="nav-link-inner--text">Loglar</strong>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -</p>
        </footer>
    </div>
    <!-- Core -->
    <script src="~/assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    <script src="~/assets/vendor/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <!-- Argon JS -->
    <script src="~/assets/js/argon.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

Ticket/Views/Shared/_Success.cshtml
@model List<string>
<div class="alert alert-@Model[0] alert-dismissible fade show" role="alert">
    @Model[1]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>